### PR TITLE
Add support to set default date filter start and end to support other Date/DateTime types.

### PR DESCRIPTION
**Pull request by shaneburrell**
The default hard set in code does not work with smalldatetime in MS SQL. This makes it configurable.

### CODE REVIEW

**Comment by shaneburrell** [comment]
>

**Comment by shaneburrell** [comment]
The package updates and PR's were quite a ways behind so I needed to fork as it was holding up use in projects.  If development picks back up here I would rather not maintain my own fork and package but for now it was really my only option.

**Comment by thyseus** [comment]
This looks very good to me. I will merge this tomorrow when i am in office and i will release a new minor version then ! 
No need to fork, i try to look more often into the pull requests now.

**Comment by shaneburrell** [comment]
Note that since posting the PR I've done quite a bit in my master branch.  You may want to just peel that one change.

**Comment by thyseus** [comment]
You mean, i should choose "squash and merge" to keep the git history clean, i assume.

**Pull request merged**
