### PR TITLE
Add "Row Index" column type

### PR DESCRIPTION
**Pull request by NikarashiHatsu**
This feature is unlikely to be used. But to be honest I'm really looking forward to how to add Laravel's `$loop->increment` into this package. I read the documentation, and I don't see any function related to the incremental feature.

I think it could be nice to have such a feature in this package because it helps me a lot.

The usage is simply by using:
```php
\Mediconesystems\LivewireDatatables\Column::index($this);
```

### CODE REVIEW

**Comment by MuhamadAhmadin** [comment]
> This feature is unlikely to be used. But to be honest I'm really looking forward to how to add Laravel's `$loop->increment` into this package. I read the documentation, and I don't see any function related to the incremental feature.
> 
> I think it could be nice to have such a feature in this package because it helps me a lot.
> 
> The usage is simply by using:
> 
> ```
> \Mediconesystems\LivewireDatatables\Column::index($this);
> ```

I agree with that

**Comment by thyseus** [comment]
It is not unlikely to be used. I have a real use case for this. Scores inside a Highscore table with place 1 at the top and the other players descending. Thanks for Implementing :)

**Comment by NikarashiHatsu** [comment]
I couldn't believe my first PR has just merged. Thanks a lot! :tada:

**Comment by alexandergziresis** [comment]
> I couldn't believe my first PR has just merged. Thanks a lot! 🎉

How i use this new feature, isn't in documentation, thanks!

**Comment by thyseus** [comment]
I added the a small hint to that feature in the documentation:

https://github.com/MedicOneSystems/livewire-datatables/pull/406

**Comment by NikarashiHatsu** [comment]
Apparently, the Row Index is failing when it is sorted as descending.
There's no error, but the number will stay remain on 1. If there's someone who could make it "reversed", I would greatly appreciate it.

**Pull request merged**
