### PR TITLE
Get DB connection from builder

### PR DESCRIPTION
**Pull request by saulens22**
When using non-default connection model, sort expression is still derived from default connection.

In my project, I use MySQL as default connection and SQLSRV as model connection. Sort queries always fail with ```Incorrect syntax near '`'.```

This PR is supposed to fix this problem. It might be possible that `DB::raw()` calls might be affected by similar problems, I will look into it.

### CODE REVIEW

**Comment by thyseus** [comment]
Thanks a lot for your contribution. I will review and test it with my projects that have datatables implemented in my office soon (next days) and will give feedback / merge it.

**Comment by saulens22** [comment]
I am still finding bugs, hope I will squash them by that time

**Comment by saulens22** [comment]
I should note that this is a quick and dirty workaround. It should be possible to get DB connection (or at least name) from the model itself, but as far as I know there are no static methods for that.

**Comment by thyseus** [comment]
Is https://github.com/MedicOneSystems/livewire-datatables/pull/450 possibly fixing this issue ?

**Pull request closed without merging**
