### PR TITLE
Mass action support

### PR DESCRIPTION
**Pull request by tomshaw**
This is completely opinionated. Suggestions are welcome.

```
    public function buildActions()
    {
        return [

            Action::value('edit')->label('Edit Selected')->group('Default Options')->callback(function ($mode, $items) {
                $this->editHandler($mode, $items);
            }),

            Action::value('update')->label('Update Selected')->group('Default Options')->callback(function ($mode, $items) {
                $this->editHandler($mode, $items);
            }),

            Action::groupBy('Export Options', function () {
                return [
                    Action::value('csv')->label('Export CSV')->export('SalesOrders.csv'),
                    Action::value('html')->label('Export HTML')->export('SalesOrders.html'),
                    Action::value('xlsx')->label('Export XLSX')->export('SalesOrders.xlsx')->styles($this->exportStyles)->widths($this->exportWidths)
                ];
            }),
        ];
    }

    public function editHandler($mode, $items)
    {

    }

    public function getExportStylesProperty()
    {
        return [
            '1'  => ['font' => ['bold' => true]],
            'B2' => ['font' => ['italic' => true]],
            'C'  => ['font' => ['size' => 16]],
        ];
    }

    public function getExportWidthsProperty()
    {
        return [
            'A' => 55,
            'B' => 45,
        ];
    }
```

### CODE REVIEW

**Comment by thyseus** [comment]
+1 i like the idea and implementation of this feature.

**Comment by tomshaw** [comment]
Appreciate! Nice library by the way! I think I merged it correctly. Haven't looked at it in a while. Thanks again! 👍

**Comment by thyseus** [comment]
Hey, @tomshaw i want to merge your code; i have added some documentation for it. Since you are speaking english natively, could you please quickly check if i have done that right ?

Thanks a lot for your contribution !

**Comment by tomshaw** [comment]
@thyseus Just read it looks great. 👍

**Comment by tomshaw** [comment]
You may want to add the export styles/width methods for example purposes. 

```
public function getExportStylesProperty()
    {
        return [
            '1'  => ['font' => ['bold' => true]],
            'B2' => ['font' => ['italic' => true]],
            'C'  => ['font' => ['size' => 16]],
        ];
    }

    public function getExportWidthsProperty()
    {
        return [
            'A' => 55,
            'B' => 45,
        ];
    }
```

**Comment by thyseus** [comment]
@tomshaw Ok, i will add the style documentation block to the README.md and merge the MR although my personal opinion is to change the styles in the view file that has been published from the vendor/ folder to your specific project.

**Pull request merged**
