### PR TITLE
Added ActionsColumn

### PR DESCRIPTION
**Pull request by tiagosimoesdev**
You can call like this : 

```
ActionsColumn::actions()->with([
                'view'  => ['users.show',['username'],
                'edit'  => ['users.edit'],
                'delete'    =>  ['users.delete']
            ])->label('ActionsTitle')
```
`with` accepts an array with

`['BUTTON_NAME' => ['ROUTE_NAME',['PARAM1',PARAM2..]`

 or simply

` ['BUTTON_NAME' =>'[ROUTE_NAME']` ( it will add id if not set params )

The user can add his own buttons by extending `ActionsColumn` and adding a function like this : 

```
<?php


namespace App;

use Mediconesystems\LivewireDatatables\ActionsColumn;

class MyActionsColumn extends ActionsColumn

{

    public function printRoute($route_name, $params = null)
    {
        $this->routes['print'] = [$route_name, $params];
    }
}

?>
```

and creating the blade file in `datatables/buttons/print.blade.php`

There are 4 new files:

`//actions.blade.php`
just to loop and show the right buttons

and 3 buttons
`view.blade.php` `edit.blade.php` and `delete.blade.php`

### CODE REVIEW

**Comment by danielbehrendt** [comment]
@tiagosimoesdev Just one thing: I would name it in singular `ActionColumn`

**Comment by tiagosimoesdev** [comment]
@danielbehrendt  since it could have more than 1 action , I guess it's more easy to read that you can add more than 1 action to that column.

**Comment by danielbehrendt** [comment]
> @danielbehrendt since it could have more than 1 action , I guess it's more easy to read that you can add more than 1 action to that column.

Up to you, that just what I think :)

**Comment by marksalmon** [comment]
I've given this a lot of thought, and I can't keep coming back to questioning whether this is needed.

Given that most users will have to customise the actions to suit their own application, and there will have to be lots of configurable options to handle different actions and endpoints etc. This can already be achieved by using:

```php
Column::name('id')->view('datatable.actions');
```
and then providing your own blade file with your own buttons and actions. 

Can anyone give me any strong argument for adding the complexity to the package rather than users rolling their own implementation?

**Comment by marksalmon** [comment]
Hi,

Sorry for the long delay on this one, and thanks for your contribution. I know I encouraged this PR but I've been round and round in circles trying to work out the best way to implement this without introducing too much complexity. 

Ultimately I have decided that it's just not worth the complexity of trying to anticipate every use case. This PR is very good, but assumes that 'show' and 'edit' actions will be links that return new routes. This will only get more complex if users want different functionality such as an edit modal, or custom actions, or different parameters like in your example above.

The other thing is that this is all already doable with the existing callback column API, you can pass whatever columns you like to whatever view you like. I have added a [page](https://livewire-datatables.com/actions) to the demo site that achieves the same result using:

```php
Column::callback(['id', 'name'], function ($id, $name) {
    return view('table-actions', ['id' => $id, 'name' => $name]);
})
```

with a custom ```resources/views.table-actions.blade.php``` file.

If anyone feels especially strongly about this, and can give me any good reasons why I'm wrong, then please re-open.

**Pull request closed without merging**
