### PR TITLE
L10 compatibility

### PR DESCRIPTION
**Pull request by johnnuman**
I was successfully able to install and run the package with Laravel v10. There were no issues or errors during `composer update`.

### CODE REVIEW

**Comment by RalpinMcDjango** [comment]
I can also confirm i've updated my project to laravel 10 with these changes and everything is working as expected.

Thanks John

**Comment by Dandrum** [comment]
Can please someone approve this pull request.

**Comment by RalpinMcDjango** [comment]
Thanks for merging the release, I suggest for others wanting to ```composer update``` that you create a release or tags for this merge.

**Comment by thyseus** [comment]
@RalpinMcDjango done:

https://github.com/MedicOneSystems/livewire-datatables/releases/tag/v0.10.1

Glad to see this package is still in use by people :)

**Comment by Dandrum** [comment]
What did you change to make it work with Laravel 10.

I use Laravel 10.4 in a Docker PHP 8.2 FPM with alpine.
And got this error:

```
Problem 1
    - Root composer.json requires php ^8.2 but your php version (8.1.3) does not satisfy that requirement.
  Problem 2
    - phpoffice/phpspreadsheet[1.15.0, ..., 1.28.0] require ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.1.3) does not satisfy that requirement.
    - mediconesystems/livewire-datatables v0.10.1 requires maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.48].
    - maatwebsite/excel[3.1.28, ..., 3.1.30] require phpoffice/phpspreadsheet 1.16.* -> satisfiable by phpoffice/phpspreadsheet[1.16.0].
    - maatwebsite/excel[3.1.31, ..., 3.1.48] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.28.0].
    - maatwebsite/excel 3.1.27 requires phpoffice/phpspreadsheet ^1.16 -> satisfiable by phpoffice/phpspreadsheet[1.16.0, ..., 1.28.0].
    - maatwebsite/excel 3.1.26 requires phpoffice/phpspreadsheet ^1.15 -> satisfiable by phpoffice/phpspreadsheet[1.15.0, ..., 1.28.0].
    - Root composer.json requires mediconesystems/livewire-datatables ^0.10.1 -> satisfiable by mediconesystems/livewire-datatables[v0.10.1].

```

**Comment by Dandrum** [comment]
I run in following Problem with Docker FPM Php 8.2 and Laravel 10.4

```
#0 3.996   Problem 1
#0 3.996     - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.2.4) does not satisfy that requirement.
#0 3.996     - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.2.4) does not satisfy that requirement.
#0 3.996     - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.4) does not satisfy that requirement.
#0 3.996     - Root composer.json requires mediconesystems/livewire-datatables ^0.10.1 -> satisfiable by mediconesystems/livewire-datatables[v0.10.1].

```

**Comment by Sajjad-Arjmand** [comment]
> I run in following Problem with Docker FPM Php 8.2 and Laravel 10.4
> 
> ```
> #0 3.996   Problem 1
> #0 3.996     - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.2.4) does not satisfy that requirement.
> #0 3.996     - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.2.4) does not satisfy that requirement.
> #0 3.996     - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.2.4) does not satisfy that requirement.
> #0 3.996     - Root composer.json requires mediconesystems/livewire-datatables ^0.10.1 -> satisfiable by mediconesystems/livewire-datatables[v0.10.1].
> ```

same here

**Pull request merged**
